### ISSUE TITLE
multiple lines on number plate

### ISSUE THREAD

**Issue by william-bohannan** [ablanco1950/LicensePlate_Yolov8_Filters_PaddleOCR#1]
only seems to get a single line on the number plate, number plates here have multiple lines, for example below

![1682460827-numberplate-0](https://user-images.githubusercontent.com/569065/234669508-1da0a787-4199-4739-8950-b6e9a23e394b.jpg)

have tried using pytesseract to detect the multiple lines and then using paddle with little success, any thoughts on this?

**Comment by ablanco1950** [comment]
Indeed, it still needs to consider the case of license plates with several
lines.

I have prepared a new version that considers this case and incorporates
some performance improvements through new filters.

Tomorrow i will clean it up a bit and  upload it to github. I will Notify
to this email address when I have done so.

It has given me a great joy to receive this observation to my modest work,
and I encourage you to send me all the ones you consider.

Thank you very much and best regards.

Alfonso Blanco Garcia

**Comment by ablanco1950** [comment]
I just uploaded to github a new version of the program called GetNumberInternationalLicensePlate_Yolov8_Filters_PaddleOCR_V1.py that considers the case of license plates with multiple lines and also multiple license plates in one image.
I have done the tests with the images from this other github project https://github.com/mrzaizai2k/VIETNAMESE_LICENSE_PLATE/tree/master/data/image
Since I keep the old version of the program: GetNumberInternationalLicensePlate_Yolov8_Filters_PaddleOCR.py (without the V1 of the new one), I can explain the changes:

It was about that in the GetPaddleOcr subroutine, in line 247 result = result[0] it only considered the first occurrence of the obtained result. It is solved in the new one by introducing a loop in line 234 that treats all the detected lines.

Do not hesitate to communicate any observation.

**Comment by william-bohannan** [comment]
many thanks works great!
