### ISSUE TITLE
license plate border removal and general pre-clean

### ISSUE THREAD

**Issue by william-bohannan** [ablanco1950/LicensePlate_Yolov8_Filters_PaddleOCR#2]
it is possible to clean the number plate so the OCR works better?  for example:

 - the "N" on the plate is not recognised as it touches the border (think there is a screw there), perhaps filter borders after we rotate it
 - the "o" on the plate sometimes comes up as a "0" or "o", perhaps filter thin lines?

![1682460830-numberplate-0](https://user-images.githubusercontent.com/569065/235269400-9b40de55-afc7-4b4f-9360-398c3d5d023c.jpg)

Also i find upscaling the image using the following really increases the detection rate:

ocv_model = cv2.dnn_superres.DnnSuperResImpl_create()
ocv_weight = 'EDSR_x4.pb'
ocv_model.readModel(ocv_weight)
ocv_model.setModel('edsr', 4)

def img_upscale(img, verbose=False):
  '''
  upscale the image using OCV
  '''
  if option_upscale:
    if verbose:
      cv2.imshow(f"before", img)
    # upscale
    img = ocv_model.upsample(img)
    if verbose:
      cv2.imshow(f"after", img)
      cv2.waitKey (0)
      cv2.destroyAllWindows ()
    print(f"  :: upscaled using AI")
  else:
    print(f"  :: selected to skip AI upscaling")

  return img

**Comment by ablanco1950** [comment]
Thank you very much for the observations and indication of improvement.
I get to it and I'll answer

**Comment by ablanco1950** [comment]
I have uploaded to the project on github the program TestWilburImage.py with which you can check the correct detection of the plate of the received image, also uploaded to the project as WilburImage.jpg

I have also introduced the changes in the main program of the project : 
 GetNumberInternationalLicensePlate_Yolov8_Filters_PaddleOCR_V1.py, so that tests can be done with the complete image of the vehicle, not just the license plate.

The changes have consisted of a Gaussian blur and dilate prior to the execution of the filter that I call concat obtained from
# https://medium.com/practical-data-science-and-engineering/image-kernels-88162cb6585d
and to a slight adjustment of the length in the x-axis of the plate.

The tests with the high resolution filter that you proposed have not given me results and implied an unaffordable time (perhaps I have not used it correctly)

**Comment by william-bohannan** [comment]
thanks will give it a go.  note for the upscale there are different models, i am having success with FSRCNN as much quicker.

```
# Opencv
ocv_model = cv2.dnn_superres.DnnSuperResImpl_create()
ocv_weight = '/media/sda1/ai/models/upscale/FSRCNN_x4.pb'   # search directory for best weight
ocv_model.readModel(ocv_weight)
if ocv_weight == "/media/sda1/ai/models/upscale/EDSR_x4.pb":
  ocv_model.setModel('edsr', 4)   # most accurate, slow (not realtime)
elif ocv_weight == "/media/sda1/ai/models/upscale/ESPCN_x4.pb":
  ocv_model.setModel('espcn', 4)   # best for realtime
elif ocv_weight == "/media/sda1/ai/models/upscale/FSRCNN_x4.pb":
  ocv_model.setModel('fsrcnn', 4)  # best for largest upscale
elif ocv_weight == "/media/sda1/ai/models/upscale/LapSRN_x8.pb":
  ocv_model.setModel('lapsrn', 8)  # best for realtime
else:
  print("no ai upscaler weights found")
  quit(1)

  def img_upscale(self, img, verbose=False):
    '''
    upscale the image using OCV: 
    https://learnopencv.com/super-resolution-in-opencv/
    '''
    start = time.time()
    status = "\033[32mPASS\033[0m"
    if option_upscale:
      if verbose:
        cv2.imshow(f"before", img)
      img = ocv_model.upsample(img) # upscale
      if verbose:
        cv2.imshow(f"after", img)
        cv2.waitKey (0)
        cv2.destroyAllWindows ()
    else:
      status = "SKIP"
    print(f"  :: {status} :: upscaled using AI, {round(time.time() - start,3)}s")
    return img   
```

**Comment by ablanco1950** [comment]
Thank you, i´ll try it

**Comment by ablanco1950** [comment]
I have modified the program GetNumberInternationalLicensePlate_Yolov8_Filters_PaddleOCR_V1.py
  so try the suggested FSRCNN filter

Although a good hit rate is achieved with this filter, there are images that are not recognized with this filter, so I maintain the system of dealing with several filters and choosing the license plate number that has been recognized the most times.
 
A general pre-cleaning produces good results in some images and not in others. Therefore, each image, according to its characteristics, is associated with a cleaning and a specific type of filter.

If I can't improve results, I plan to train a neural network so that it associates a code with each image depending on its cleaning treatment and recognition filter.

**Comment by william-bohannan** [comment]
totally agree, is super quick with just the resize.  using all 10 filters is still very quick and then use Counter to get the most repeated result.

```
        # find highest result, texts is a list of the numberplates
        counter = Counter(texts)   
        most_frequent = counter.most_common(1)
        text_count = 0
        text_found = ""
        if len(texts) > 0:
            
            # most frequent
            text_count = most_frequent[0][1]
            text_found = most_frequent[0][0]
            print(f"  :: {text_found} found {text_count} times")
```
